// <auto-generated />
namespace CMS_webAPI.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserProfile_3Props : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserProfile_3Props));
        
        string IMigrationMetadata.Id
        {
            get { return "201609031051261_UserProfile_3Props"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
